version: 0.2

env:
  variables:
    TEST_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"


phases:
  install:
    commands:
      - echo Java
      - echo $JAVA_HOME
      - echo Installing maven
      - echo $TEST_HOME
      - echo Installing maven
      - echo `mvn --version`
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo "Done installing"

  build:
    commands:
      - mvn --version
