version: 0.2

env:
  variables:
    APP_NAME: "CodeBuild Test"


phases:
  install:
    commands:
      - echo $JAVA_HOME
      - mvn --version
    finally:
      - echo "Done installing"

  build:
    commands:
      - mvn --batch-mode package
